"use client";

import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Loader2, Save, Send } from "lucide-react";
import { toast } from "sonner";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { aiSummaryService } from "@/services/ai-summary-service";
import { getApiErrorMessage } from "@/lib/api-client";
import type { AISummary } from "@/types/api";

const STATUS_VARIANT: Record<string, "warning" | "secondary" | "success" | "default"> = {
  pending_review: "warning",
  reviewed: "secondary",
  shared: "success",
  outdated: "default",
};

const editSchema = z.object({ text: z.string().min(1, "Summary text can't be empty") });
type EditFormValues = z.infer<typeof editSchema>;

export function SummaryReviewPanel({
  summary,
  onShare,
}: {
  summary: AISummary;
  onShare: () => void;
}) {
  const queryClient = useQueryClient();
  const currentText = summary.edited_summary_text ?? summary.summary_text;

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isDirty },
  } = useForm<EditFormValues>({
    resolver: zodResolver(editSchema),
    defaultValues: { text: currentText },
  });

  useEffect(() => {
    reset({ text: currentText });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [summary.id, currentText]);

  const isEditable = summary.status === "pending_review" || summary.status === "reviewed";
  const isConfirmable = summary.status === "pending_review" || summary.status === "reviewed";
  const isShareable = summary.status === "reviewed" || summary.status === "shared";

  const saveEditMutation = useMutation({
    mutationFn: (text: string) => aiSummaryService.saveEdit(summary.id, text),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ai-summaries"] });
      toast.success("Edit saved.");
    },
    onError: (error) => toast.error(getApiErrorMessage(error, "Unable to save your edit.")),
  });

  const confirmMutation = useMutation({
    mutationFn: () => aiSummaryService.confirm(summary.id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ai-summaries"] });
      toast.success("Summary confirmed. You can now share it with a doctor.");
    },
    onError: (error) => toast.error(getApiErrorMessage(error, "Unable to confirm this summary.")),
  });

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          Summary
          <Badge variant={STATUS_VARIANT[summary.status] ?? "secondary"}>
            {summary.status.replace("_", " ")}
          </Badge>
        </CardTitle>
        <span className="text-xs text-muted-foreground">
          Generated {new Date(summary.created_at).toLocaleString()}
        </span>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <Alert variant="warning">
          <AlertTriangle />
          <AlertTitle>AI-assisted, not verified</AlertTitle>
          <AlertDescription>
            This summary was generated by AI from your health data. Review it carefully and edit
            anything that isn&apos;t accurate before confirming or sharing it with a doctor.
          </AlertDescription>
        </Alert>

        <form
          onSubmit={handleSubmit((values) => saveEditMutation.mutate(values.text))}
          className="flex flex-col gap-2"
          noValidate
        >
          <Textarea
            rows={12}
            disabled={!isEditable}
            aria-invalid={Boolean(errors.text)}
            {...register("text")}
          />
          {errors.text && <p className="text-sm text-destructive">{errors.text.message}</p>}
          {isEditable && (
            <Button
              type="submit"
              variant="outline"
              size="sm"
              className="self-start"
              disabled={!isDirty || saveEditMutation.isPending}
            >
              {saveEditMutation.isPending ? <Loader2 className="animate-spin" /> : <Save />}
              Save edit
            </Button>
          )}
        </form>

        <div className="flex flex-wrap gap-2">
          <Button
            disabled={!isConfirmable || confirmMutation.isPending}
            onClick={() => confirmMutation.mutate()}
          >
            {confirmMutation.isPending ? (
              <Loader2 className="animate-spin" />
            ) : (
              <CheckCircle2 />
            )}
            Confirm
          </Button>
          <Button variant="outline" disabled={!isShareable} onClick={onShare}>
            <Send /> Share with doctor
          </Button>
        </div>
        {!isConfirmable && summary.status === "shared" && (
          <p className="text-xs text-muted-foreground">This summary has already been shared.</p>
        )}
      </CardContent>
    </Card>
  );
}
