"""medical records, ocr, medications, allergies, conditions, doctors, appointments, timeline, health snapshots

Revision ID: aa8aa52fe4ac
Revises: 929a71e5ab2b
Create Date: 2026-09-25 15:29:15.302277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8aa52fe4ac'
down_revision: Union[str, None] = '929a71e5ab2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_notes',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_notes_patient_id'), 'timeline_notes', ['patient_id'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_reminders_medication_id'), 'medication_reminders', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_reminders_patient_id'), 'medication_reminders', ['patient_id'], unique=False)
    # server_default so this backfills existing rows safely (they predate
    # the "review required" state and are treated as not-yet-reviewed).
    op.add_column(
        'document_extractions',
        sa.Column(
            'status', sa.String(length=30), nullable=False, server_default='pending_review'
        ),
    )
    op.alter_column('document_extractions', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_extractions', 'status')
    op.drop_index(op.f('ix_medication_reminders_patient_id'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_medication_id'), table_name='medication_reminders')
    op.drop_table('medication_reminders')
    op.drop_index(op.f('ix_timeline_notes_patient_id'), table_name='timeline_notes')
    op.drop_table('timeline_notes')
    # ### end Alembic commands ###
