"""ai summary review workflow

Revision ID: ef4a04efe62e
Revises: aa8aa52fe4ac
Create Date: 2026-09-25 15:44:55.700425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4a04efe62e'
down_revision: Union[str, None] = 'aa8aa52fe4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_summaries', sa.Column('edited_summary_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_summaries', 'edited_summary_text')
    # ### end Alembic commands ###
